---
title: Balance of payments
subtitle: Data - OECD
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: true
    toc: true
    theme: flatly
    embed-resources: false
editor: source
---

```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
load("BOP.RData")
load("BOP_var.RData")
load("../../flags/colors.RData")

metadata_load("ACCOUNTING_ENTRY", "CL_ACCOUNTING_ENTRY", data = BOP_var)
metadata_load("REF_AREA", "CL_AREA", data = BOP_var)
metadata_load("FREQ", "CL_FREQ", data = BOP_var)
metadata_load("MEASURE", "CL_BOP6_ITEM", data = BOP_var)
metadata_load("FS_ENTRY", "CL_FS_ENTRY", data = BOP_var)
metadata_load("ADJUSTMENT", "CL_ADJUSTMENT", data = BOP_var)
metadata_load("UNIT_MEASURE", "CL_UNIT_MEASURE", data = BOP_var)

code_names <-  BOP_var@codelists@codelists %>%
  vapply(., function(x) x@id, "character") %>%
  as_tibble %>%
  arrange(value) %>%
  mutate(blank = NA) %>%
  spread(value, blank)
```


# Info

```{r, echo = F}
# cd ~/iCloud/website/data/oecd; /usr/local/bin/Rscript --vanilla _download_new.R OECD.SDD.TPS DSD_BOP BOP; /usr/local/bin/R -e 'quarto::quarto_render(input = "BOP.qmd")'
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -e 'quarto::quarto_render("BOP.qmd")'
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# sh ~/iCloud/website/website_short.sh

tribble(~source, ~ dataset,
        "oecd", "BOP") %>%
  source_dataset_file_updates()
```




## Last

```{r, echo = F}
BOP %>%
  group_by(obsTime) %>%
  summarise(Nobs = n()) %>%
  arrange(desc(obsTime)) %>%
  head(1) %>%
  print_table_conditional()
```

# REF_AREA

```{r}
BOP %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  group_by(REF_AREA, Ref_area) %>%
  summarise(Nobs = n()) %>%
  arrange(-Nobs) %>%
  print_table_conditional()
```



# FREQ

```{r}
BOP %>%
  left_join(FREQ, by = "FREQ") %>%
  group_by(FREQ, Freq) %>%
  summarise(Nobs = n()) %>%
  arrange(-Nobs) %>%
  print_table_conditional()
```


# ACCOUNTING_ENTRY

```{r}
BOP %>%
  left_join(ACCOUNTING_ENTRY, by = "ACCOUNTING_ENTRY") %>%
  group_by(ACCOUNTING_ENTRY, Accounting_entry) %>%
  summarise(Nobs = n()) %>%
  arrange(-Nobs) %>%
  print_table_conditional()
```



# UNIT_MEASURE

```{r}
BOP %>%
  left_join(UNIT_MEASURE, by = "UNIT_MEASURE") %>%
  group_by(UNIT_MEASURE, Unit_measure) %>%
  summarise(Nobs = n()) %>%
  arrange(-Nobs) %>%
  print_table_conditional()
```


# MEASURE

```{r}
BOP %>%
  left_join(MEASURE, by = "MEASURE") %>%
  group_by(MEASURE, Measure) %>%
  summarise(Nobs = n()) %>%
  arrange(-Nobs) %>%
  print_table_conditional()
```

# Financial account

## EU vs. US vs. DE vs. FR

### All

```{r FA-EU27-USA-DEU-FRA}
BOP %>%
  filter(MEASURE == "FA",
         REF_AREA %in% c("USA", "EU27_2020", "DEU", "FRA"),
         FREQ == "Q",
         UNIT_MEASURE == "USD_EXC",
         ACCOUNTING_ENTRY == "N") %>%
  arrange(desc(obsTime)) %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  #filter(date >= as.Date("1999-01-01")) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Financial Account") +
  scale_color_identity() + add_4flags +
  scale_x_date(breaks = c(seq(1949, 2100, 5)) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = seq(-10000, 10000, 500)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black")
```


### 1999-

```{r CA-USDEXC-EU27-USA-DEU-FRA-1999}
BOP %>%
  filter(MEASURE == "FA",
         REF_AREA %in% c("USA", "EU27_2020", "DEU", "FRA"),
         FREQ == "Q",
         UNIT_MEASURE == "USD_EXC",
         ACCOUNTING_ENTRY == "N") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  filter(date >= as.Date("1999-01-01")) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Financial Account") +
  scale_color_identity() + add_4flags +
  scale_x_date(breaks = c(seq(1999, 2100, 5)) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = seq(-10000, 10000, 500)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black")
```



# Current account (CA, % of GDP)

## Greece, EU, US, France

### 1999-

#### Quarterly

```{r GRC-FRA-USA-EU27-1999}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("FRA", "GRC", "USA", "EU27_2020"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  filter(date >= as.Date("1999-01-01")) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_2flags +
  scale_x_date(breaks = c(seq(1990, 2100, 2)) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  geom_label(data = . %>% filter(date == max(date)),
             aes(x = date, y = obsValue, label = percent(obsValue), color = color))
```



#### Smoothed

```{r GRC-FRA-USA-EU27-1999-smoothed}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("FRA", "GRC", "USA", "EU27_2020"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  group_by(REF_AREA) %>%
  arrange(date) %>%
  mutate(obsValue = zoo::rollmean(obsValue, k = 4, fill = NA, align = "right")) %>%
  ungroup() %>%
  filter(date >= as.Date("1999-01-01")) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_4flags +
  scale_x_date(breaks = c(seq(1990, 2100, 2)) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  geom_label(data = . %>% filter(date == max(date)),
             aes(x = date, y = obsValue, label = percent(obsValue), color = color))
```

### 2003- 



#### Smoothed

```{r GRC-FRA-USA-EU27-2003-smoothed}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("FRA", "GRC", "USA", "EU27_2020", "ITA"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  group_by(REF_AREA) %>%
  arrange(date) %>%
  mutate(obsValue = zoo::rollmean(obsValue, k = 4, fill = NA, align = "right")) %>%
  ungroup() %>%
  filter(date >= as.Date("2003-01-01")) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_5flags +
  scale_x_date(breaks = c(seq(1990, 2100, 2)) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black")
```


## Greece, US, France

### 1999-

#### Quarterly

```{r GRC-FRA-USA-1999}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("FRA", "GRC", "USA"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  filter(date >= as.Date("1999-01-01")) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_2flags +
  scale_x_date(breaks = c(seq(1990, 2100, 2)) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  geom_label(data = . %>% filter(date == max(date)),
             aes(x = date, y = obsValue, label = percent(obsValue), color = color))
```



#### Smoothed

```{r GRC-FRA-USA-1999-smoothed}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("FRA", "GRC", "USA"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  group_by(REF_AREA) %>%
  arrange(date) %>%
  mutate(obsValue = zoo::rollmean(obsValue, k = 4, fill = NA, align = "right")) %>%
  ungroup() %>%
  filter(date >= as.Date("1999-01-01")) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_3flags +
  scale_x_date(breaks = c(seq(1990, 2100, 2)) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  geom_label(data = . %>% filter(date == max(date)),
             aes(x = date, y = obsValue, label = percent(obsValue), color = color))
```

## EU vs. US

### All

```{r CA}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("USA", "EA20"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EA20", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_2flags +
  scale_x_date(breaks = seq(1920, 2100, 5) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black")
```



### 2012-

```{r CA-USA-EA20-2012}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("USA", "EA20"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EA20", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  rename(Location = Ref_area) %>%
  filter(date >= as.Date("2013-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_2flags +
  scale_x_date(breaks = seq(1920, 2100, 1) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black")
```



## EU27_2020 vs. US

### All

```{r CA-EU27-USA}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("USA", "EU27_2020"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_2flags +
  scale_x_date(breaks = seq(1920, 2100, 5) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black")
```



### 1999-

```{r CA-EU27-USA-1999}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("USA", "EU27_2020"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  filter(date >= as.Date("1999-01-01")) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_2flags +
  scale_x_date(breaks = c(seq(1990, 2100, 2)) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  geom_label(data = . %>% filter(date == max(date)),
             aes(x = date, y = obsValue, label = percent(obsValue), color = color))
```


## EU vs. US vs. IT


### 1999-

```{r CA-EU27-USA-ITA-1999}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("USA", "EU27_2020", "ITA"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  filter(date >= as.Date("1999-01-01")) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_3flags +
  scale_x_date(breaks = c(seq(1997, 2100, 5), seq(1999, 2100, 5)) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black")
```



## EU vs. US vs. DE vs. FR


### All

```{r CA-EU27-USA-DEU-FRA}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("USA", "EU27_2020", "DEU", "FRA"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  #filter(date >= as.Date("1999-01-01")) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_4flags +
  scale_x_date(breaks = c(seq(1949, 2100, 5)) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black")
```


### 1999-

#### Quarterly

```{r CA-EU27-USA-DEU-FRA-1999}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("USA", "EU27_2020", "DEU", "FRA"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  filter(date >= as.Date("1999-01-01")) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_4flags +
  scale_x_date(breaks = c(seq(1997, 2100, 2)) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black")
```

#### Smoothed

#### Quarterly

```{r CA-EU27-USA-DEU-FRA-1999-smoothed}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("USA", "EU27_2020", "DEU", "FRA"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  filter(date >= as.Date("1999-01-01")) %>%
  group_by(REF_AREA) %>%
  arrange(date) %>%
  mutate(obsValue_roll4 = zoo::rollmean(obsValue, k = 4, fill = NA, align = "right")) %>%
  ungroup() %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue_roll4, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_4flags +
  scale_x_date(breaks = c(seq(1997, 2100, 2)) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black")
```



## EU vs. US vs. DE


### All

```{r CA-EU27-USA-DEU}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("USA", "EU27_2020", "DEU"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  #filter(date >= as.Date("1999-01-01")) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_4flags +
  scale_x_date(breaks = c(seq(1949, 2100, 5)) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black")
```


### 1999-

```{r CA-EU27-USA-DEU-1999}
BOP %>%
  filter(MEASURE == "CA",
         REF_AREA %in% c("USA", "EU27_2020", "DEU"),
         FREQ == "Q",
         UNIT_MEASURE == "PT_B1GQ") %>%
  quarter_to_date() %>%
  left_join(REF_AREA, by = "REF_AREA") %>%
  arrange(desc(date)) %>%
  mutate(Ref_area = ifelse(REF_AREA == "EU27_2020", "Europe", Ref_area)) %>%
  left_join(colors, by = c("Ref_area" = "country")) %>%
  mutate(color = ifelse(REF_AREA == "USA", color2, color)) %>%
  mutate(obsValue = obsValue/100) %>%
  filter(date >= as.Date("1999-01-01")) %>%
  rename(Location = Ref_area) %>%
  #filter(date <= as.Date("2021-01-01")) %>%
  ggplot(.) + geom_line(aes(x = date, y = obsValue, color = color)) + 
  theme_minimal() + xlab("") + ylab("Current Account, % of GDP") +
  scale_color_identity() + add_3flags +
  scale_x_date(breaks = c(seq(1997, 2100, 5), seq(1999, 2100, 5)) %>% paste0("-01-01") %>% as.Date,
               labels = date_format("%Y")) +
  scale_y_continuous(breaks = 0.01*seq(-60, 60, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black")
```