---
title: Euro/ECU exchange rates - daily data
subtitle: Data - Eurostat
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: true
    toc: true
    theme: flatly
    embed-resources: false
editor: source
---

```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
ert_bil_eur_d <- get_eurostat("ert_bil_eur_d", stringsAsFactors = F, cache = F) %>%
  rename(date = TIME_PERIOD) %>%
  select_if(~ n_distinct(.) > 1)

currency <- get_eurostat_dic("currency", lang = "en") %>%
  setNames(c("currency", "Currency"))
names <- names(ert_bil_eur_d)
load(here::here("flags", "colors.RData"))
```



# Info





# USD, CHF, GBP

## All

```{r USD-CHF-GBP}
ert_bil_eur_d %>%
  filter(currency %in% c("USD", "CHF", "GBP")) %>%
  left_join(currency, by = "currency") %>%
  mutate(Geo = case_when(currency == "USD" ~ "United States",
                         currency == "CHF" ~ "Switzerland",
                         currency == "GBP" ~ "United Kingdom")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_3flags +
  scale_x_date(breaks = as.Date(paste0(seq(1960, 2030, 5), "-01-01")),
               labels = date_format("%Y")) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(0, 10, 0.5),
                     labels = dollar_format(p = "", su = "/€")) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```

## 10 years

```{r USD-CHF-GBP-10-years}
ert_bil_eur_d %>%
  filter(currency %in% c("USD", "CHF", "GBP")) %>%
  left_join(currency, by = "currency") %>%
  
  filter(date >= Sys.Date() - years(10)) %>%
  mutate(Geo = case_when(currency == "USD" ~ "United States",
                         currency == "CHF" ~ "Switzerland",
                         currency == "GBP" ~ "United Kingdom")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_3flags +
  scale_x_date(breaks = "6 months",
               labels = date_format("%b %Y")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(0, 10, 0.05),
                     labels = dollar_format(p = "", su = "/€")) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```

## 2 years

```{r USD-CHF-GBP-2-years}
ert_bil_eur_d %>%
  filter(currency %in% c("USD", "CHF", "GBP")) %>%
  left_join(currency, by = "currency") %>%
  
  filter(date >= Sys.Date() - years(2)) %>%
  mutate(Geo = case_when(currency == "USD" ~ "United States",
                         currency == "CHF" ~ "Switzerland",
                         currency == "GBP" ~ "United Kingdom")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_3flags +
  scale_x_date(breaks = "1 month",
               labels = date_format("%d %b %Y")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(0, 10, 0.05),
                     labels = dollar_format(p = "", su = "/€")) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```

## 1 year

```{r USD-CHF-GBP-1-year}
ert_bil_eur_d %>%
  filter(currency %in% c("USD", "CHF", "GBP")) %>%
  left_join(currency, by = "currency") %>%
  
  filter(date >= Sys.Date() - years(1)) %>%
  mutate(Geo = case_when(currency == "USD" ~ "United States",
                         currency == "CHF" ~ "Switzerland",
                         currency == "GBP" ~ "United Kingdom")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_3flags +
  scale_x_date(breaks = "1 month",
               labels = date_format("%d %b %Y")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(0, 10, 0.05),
                     labels = dollar_format(p = "", su = "/€")) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```


## 1 month

```{r USD-CHF-GBP-1-month}
ert_bil_eur_d %>%
  filter(currency %in% c("USD", "CHF", "GBP")) %>%
  left_join(currency, by = "currency") %>%
  
  filter(date >= Sys.Date() - months(1)) %>%
  mutate(Geo = case_when(currency == "USD" ~ "United States",
                         currency == "CHF" ~ "Switzerland",
                         currency == "GBP" ~ "United Kingdom")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_3flags +
  scale_x_date(breaks = "1 day",
               labels = date_format("%d %b %Y")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(0, 10, 0.02),
                     labels = dollar_format(p = "", su = "/€")) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```




# NOK, CHF

## All

```{r NOK-CHF}
ert_bil_eur_d %>%
  filter(currency %in% c("NOK", "CHF")) %>%
  left_join(currency, by = "currency") %>%
  
  mutate(Geo = case_when(currency == "NOK" ~ "Norway",
                         currency == "CHF" ~ "Switzerland")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_2flags +
  scale_x_date(breaks = as.Date(paste0(seq(1960, 2030, 5), "-01-01")),
               labels = date_format("%Y")) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(0, 10, 0.5),
                     labels = dollar_format(p = "", su = "/€")) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```


## 10 years

```{r NOK-CHF-10-years}
ert_bil_eur_d %>%
  filter(currency %in% c("NOK", "CHF")) %>%
  left_join(currency, by = "currency") %>%
  
  filter(date >= Sys.Date() - years(10)) %>%
  mutate(Geo = case_when(currency == "NOK" ~ "Norway",
                         currency == "CHF" ~ "Switzerland")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  group_by(currency) %>%
  arrange(date) %>%
  mutate(values = 100*values/values[1]) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_2flags +
  scale_x_date(breaks = as.Date(paste0(seq(1960, 2030, 1), "-01-01")),
               labels = date_format("%Y")) +
  #theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(0, 10, 0.05),
                     labels = dollar_format(p = "", su = "/€")) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```


## 2 years

```{r NOK-CHF-2-years}
ert_bil_eur_d %>%
  filter(currency %in% c("NOK", "CHF")) %>%
  left_join(currency, by = "currency") %>%
  
  filter(date >= Sys.Date() - years(2)) %>%
  mutate(Geo = case_when(currency == "NOK" ~ "Norway",
                         currency == "CHF" ~ "Switzerland")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  mutate(color = ifelse(Geo == "Norway", color2, color)) %>%
  group_by(currency) %>%
  arrange(date) %>%
  mutate(values = 100*values/values[1]) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_2flags +
  scale_x_date(breaks = "1 month",
               labels = date_format("%b %Y")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(10, 400, 5)) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```

# USD, CHF

## All

```{r USD-CHF}
ert_bil_eur_d %>%
  filter(currency %in% c("USD", "CHF")) %>%
  left_join(currency, by = "currency") %>%
  
  mutate(Geo = case_when(currency == "USD" ~ "United States",
                         currency == "CHF" ~ "Switzerland")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_2flags +
  scale_x_date(breaks = as.Date(paste0(seq(1960, 2030, 5), "-01-01")),
               labels = date_format("%Y")) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(0, 10, 0.5),
                     labels = dollar_format(p = "", su = "/€")) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```



## 2013-2017

```{r USD-CHF-2013-2017}
ert_bil_eur_d %>%
  filter(currency %in% c("USD", "CHF")) %>%
  left_join(currency, by = "currency") %>%
  
  filter(date >= as.Date("2013-01-01"),
         date <= as.Date("2018-01-01")) %>%
  mutate(Geo = case_when(currency == "USD" ~ "United States",
                         currency == "CHF" ~ "Switzerland")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_2flags +
  scale_x_date(breaks = as.Date(paste0(seq(1960, 2030, 1), "-01-01")),
               labels = date_format("%Y")) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(0, 10, 0.05),
                     labels = dollar_format(p = "", su = "/€", acc = 0.01)) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```


## 2014-2015

```{r USD-CHF-2014-2015}
ert_bil_eur_d %>%
  filter(currency %in% c("USD", "CHF")) %>%
  left_join(currency, by = "currency") %>%
  
  filter(date >= as.Date("2014-07-01"),
         date <= as.Date("2015-07-01")) %>%
  mutate(Geo = case_when(currency == "USD" ~ "United States",
                         currency == "CHF" ~ "Switzerland")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_2flags +
  scale_x_date(breaks = "1 month",
               labels = date_format("%b %Y")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(0, 10, 0.05),
                     labels = dollar_format(p = "", su = "/€", acc = 0.01)) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```

## 10 years

```{r USD-CHF-10-years}
ert_bil_eur_d %>%
  filter(currency %in% c("USD", "CHF")) %>%
  left_join(currency, by = "currency") %>%
  
  filter(date >= Sys.Date() - years(10)) %>%
  mutate(Geo = case_when(currency == "USD" ~ "United States",
                         currency == "CHF" ~ "Switzerland")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_2flags +
  scale_x_date(breaks = as.Date(paste0(seq(1960, 2030, 1), "-01-01")),
               labels = date_format("%Y")) +
  #theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(0, 10, 0.05),
                     labels = dollar_format(p = "", su = "/€")) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```

## 2 years

```{r USD-CHF-2-years}
ert_bil_eur_d %>%
  filter(currency %in% c("USD", "CHF")) %>%
  left_join(currency, by = "currency") %>%
  
  filter(date >= Sys.Date() - years(2)) %>%
  mutate(Geo = case_when(currency == "USD" ~ "United States",
                         currency == "CHF" ~ "Switzerland")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_2flags +
  scale_x_date(breaks = "1 month",
               labels = date_format("%d %b %Y")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(0, 10, 0.01),
                     labels = dollar_format(p = "", su = "/€")) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```

## 1 year

```{r USD-CHF-1-year}
ert_bil_eur_d %>%
  filter(currency %in% c("USD", "CHF")) %>%
  left_join(currency, by = "currency") %>%
  
  filter(date >= Sys.Date() - years(1)) %>%
  mutate(Geo = case_when(currency == "USD" ~ "United States",
                         currency == "CHF" ~ "Switzerland")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_2flags +
  scale_x_date(breaks = "1 month",
               labels = date_format("%d %b %Y")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(0, 10, 0.01),
                     labels = dollar_format(p = "", su = "/€")) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```


## 1 month

```{r USD-CHF-1-month}
ert_bil_eur_d %>%
  filter(currency %in% c("USD", "CHF")) %>%
  left_join(currency, by = "currency") %>%
  
  filter(date >= Sys.Date() - months(1)) %>%
  mutate(Geo = case_when(currency == "USD" ~ "United States",
                         currency == "CHF" ~ "Switzerland")) %>%
  left_join(colors, by = c("Geo" = "country")) %>%
  ggplot + geom_line(aes(x = date, y = values, color = color)) +
  scale_color_identity() + theme_minimal()  + add_2flags +
  scale_x_date(breaks = "1 day",
               labels = date_format("%d %b %Y")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  xlab("") + ylab("") +
  scale_y_log10(breaks = seq(0, 10, 0.01),
                     labels = dollar_format(p = "", su = "/€")) +
  geom_label(data = . %>% filter(max(date) == date),
             aes(x = date, y = values, label = round(values, 3), color = color))
```


