---
title: Météo
subtitle: Data - meteo
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: true
    toc: true
    theme: flatly
    embed-resources: false
editor: source
---

```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "fr_FR.UTF-8"))
invisible(Sys.setenv(TZ = "Europe/Paris"))
source(here::here("code/meteo.R"))
# cd ~/iCloud/website/data/meteo; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# sh ~/iCloud/website/website_short.sh
```


# Paris-Montsouris (07156)

## Par heure, 2 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_heure_par_heure("07156", from = Sys.Date() - 2)
```



## 30 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_last_days("07156", 30)
```



# Lille (07015)

## Par heure, 2 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_heure_par_heure("07015", from = Sys.Date() - 2)
```



## 30 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_last_days("07015", 30)
```

# Montagne

## Chamonix (07490)

### Par heure, 2 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_heure_par_heure("07490", from = Sys.Date() - 2)
```



### 30 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_last_days("07490", 30)
```


# Région Parisienne

## Roissy CDG (07157)

### Par heure, 2 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_heure_par_heure("07157", from = Sys.Date() - 2)
```



### 30 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_last_days("07157", 30)
```

# Marseille Marignane (07650)

## Par heure, 2 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_heure_par_heure("07650", from = Sys.Date() - 2)
```

## 30 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_last_days("07650", 30)
```
