---
title: Stations
subtitle: Data - meteo
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: true
    toc: true
    theme: flatly
    embed-resources: false
editor: source
---

```{r, echo = FALSE, message = FALSE}
source("../../code/R-markdown/init_insee.R")
# cd ~/iCloud/website/data/meteo; /usr/local/bin/R -e 'quarto::quarto_render("montsouris.qmd")'
# sh ~/iCloud/website/website_short.sh
knitr::opts_chunk$set(fig.height = 1.25*3.375, fig.width = 1.25*6, 
                      out.width="100%", out.height="100%", 
                      fig.align = "center", comment = "#",
                      echo = T, warning = F,
                      message = F, dev = c('png'))
load_data("meteo/station_list.RData")
```




# Toutes les stations

## Liste stations

```{r}
station_list %>%
  filter(!is.na(Id_OMM)) %>%
  select(num_station = 2, nom_station = 4) %>%
  mutate(url = paste0("https://www.meteo60.fr/stations-releves/station-jour-csv?station_id=-", num_station, "&date=", paste0(format(Sys.Date(), "%d/%m/%Y")))) %>%
  mutate(data = map(url, ~ fread(.) %>%
                      tail(1))) %>%
  mutate(data = lapply(data, function(df) {
    df$`Vent moyen` <- as.character(df$`Vent moyen`)
    df$`Nebulosite` <- as.character(df$`Nebulosite`)
    df$`Visibilite` <- as.character(df$`Visibilite`)
    df$`Pression_mer` <- as.character(df$`Pression_mer`)
    df$`Point_rosee` <- as.character(df$`Point_rosee`)
    df$`11` <- as.character(df$`11`)
    df$`V9` <- as.character(df$`V9`)
    df$`8` <- as.character(df$`8`)
    df$`-` <- as.character(df$`-`)
    return(df)
  })) %>%
  unnest %>%
  select(-url) %>%
  select(1, 2, 5, 10) %>%
  print_table_conditional()
```

## Tous

```{r}
fread(paste0("https://www.meteo60.fr/stations-releves/jour-csv?date=", paste0(format(Sys.Date() - days(1), "%d/%m/%Y")))) %>%
  select(-V7) %>%
  print_table_conditional()
```



