---
title: Données sur la retraite par capitalisation
metadata-files: 
  - _common_fr.yml
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "fr_FR.UTF-8"))
invisible(Sys.setenv(TZ = "Europe/Paris"))
load(here::here("flags", "colors.RData"))

`capitalisation` <- tribble(
  ~source, ~dataset,
  "yahoo",  "indices",
  "yahoo", "SP500") %>%
  arrange(source, dataset)
```

# Capitalisation

## S&P 500 et CAC 40

Rendements

```{r}
ig_d("yahoo", "indices", "SP500TR-CAC40TR-1990-log")
```

## 7 magnifiques de la tech

```{r}
ig_d("yahoo", "SP500", "magnificent-7-2010-log")
```




## S&P 500 et CAC 40

Rendements

```{r}
ig_d("yahoo", "indices", "SP500TR-CAC40TR-1990-log")
```


# Comment financer le passage à la capitalisation ?

## Déficit public ?

Déjà à -5.8% du PIB en 2024, objectif retour au dessus de -3% du PIB à l'horizon de 2029...

```{r}
ig_d("insee", "T_7301", "B9-PIB-2000")
```

## Perte de pouvoir d'achat des salaires

Double cotisation ?

```{r}
ig_d("insee", "SALAIRES-ANNUELS", "PCS-indice-CCE-4-6-IPC-IPCH-reel")
```

## Perte de pouvoir d'achat des retraites

```{r}
ig_d("ipp", "revalorisation_pension", "reval-1996-reel")
```


# Bibliographie

## En Anglais

{{< include ../publications/en/Geerolf2013.qmd >}}



