---
title: Data on commodities
subtitle: Data
lang: en
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: false
    toc: true
    theme: flatly
    embed-resources: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
editor: source
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))
`commodities` <- tribble(
  ~source, ~dataset,
  "yahoo", "commodities",
  "fred",  "energy",
  "yahoo",  "energy",
  "wb", "CMO") %>%
  arrange(source, dataset)
```

# Current

```{r, echo = F}
temp <- "https://fr.investing.com/commodities/real-time-futures" |>
  rvest::read_html() |>
  rvest::html_table(header = T, fill = T) |>
  pluck(1) %>%
  select(-1)

temp |>
  gt()|>
    tab_options(
      quarto.disable_processing = TRUE
    ) |> 
  cols_align(
    align = "center") |>
  fmt_number(
    dec_mark = ",",
    sep_mark = ".",
    decimals = 2
  ) |>
  opt_interactive(
    use_search = F,
    use_pagination = F,
    use_pagination_info = F,
    use_compact_mode = T,
    page_size_default = 20,
    page_size_values = c(5, 10, 15, 20),
    use_resizers = T,
    use_highlight = T
  # ) |>
  # cols_width(
  #   c("country_code_2") ~ px(40),
  #   c("Current Rate") ~ px(120),
  #   c("Next Meeting") ~ px(140),
  #   c("Central Bank") ~ px(280),
  #   everything() ~ px(200)
  ) |>
  gt::tab_source_note(
    source_note = gt::md(paste0("Date: ", format(Sys.time(), format = "%B %d, %Y %I:%M %p"), ". Source: <https://fr.investing.com/commodities/real-time-futures>"))
  ) |>
  gt::tab_options(table.width = "100%")
```




# Bitcoin

## Euro

```{r}
ig_d("yahoo", "commodities", "BTC-EUR-log-2021")
```



# TTF

```{r, echo = F}
# cd ~/iCloud/website/data/yahoo; /usr/local/bin/R -f "energy.R"; /usr/local/bin/R -e 'quarto::quarto_render("energy.qmd")'
# sh ~/iCloud/website/website_short.sh
```

## All

```{r}
ig_d("yahoo", "energy", "TTF")
```

## 2021-

```{r}
ig_d("yahoo", "energy", "TTF-2021")
```



## Log

```{r}
ig_d("yahoo", "energy", "TTF-log")
```

## Log, 2021-

```{r}
ig_d("yahoo", "energy", "TTF-log-2021")
```

# Weekly Oil prices, Europe

```{r, echo = F}
# cd ~/iCloud/website/data/fred; /usr/local/bin/R -f "energy.R"; /usr/local/bin/R -e 'quarto::quarto_render("energy.qmd")'
# cd ~/iCloud/website/data/fred; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
```

## All

```{r}
ig_d("fred", "energy", "MHHNGSP-PNGASEUUSDM-1990")
```


## 2017-


# Natural Gas

## Fred

```{r, echo = F}
# cd ~/iCloud/website/data/fred; /usr/local/bin/R -f "energy.R"; /usr/local/bin/R -e 'quarto::quarto_render("energy.qmd")'
# cd ~/iCloud/website/data/fred; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# sh ~/iCloud/website/website_short.sh
```

### 1990-

```{r}
ig_d("fred", "energy", "MHHNGSP-PNGASEUUSDM-1990")
```

### Last 10 years

```{r}
ig_d("fred", "energy", "MHHNGSP-PNGASEUUSDM-last-10-years")
```



## World Bank

```{r, echo = F}
# cd ~/iCloud/website/data/wb; /usr/local/bin/R -f "CMO.R"; /usr/local/bin/R -e 'quarto::quarto_render("CMO.qmd")'
# sh ~/iCloud/website/website_short.sh
```

### 2000-

```{r}
ig_d("wb", "CMO", "natural-gas-nominal-log-2000")
```


# Datasets

```{r, echo = F}
commodities |>
  source_dataset_file_updates()
```
