---
title: Analyse de la Conjoncture Économique en France
metadata-files: 
  - _common_fr.yml
---

```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "fr_FR.UTF-8"))
invisible(Sys.setenv(TZ = "Europe/Paris"))
knitr::opts_chunk$set(echo = T)
# (was: conjoncture <- tribble(~source, ~dataset, ...) -- now auto: theme_source_datasets("conjoncture"))
```

# Prévisions

## Gouvernement, 11 Septembre 2026

```{r, echo = F}
tibble(
  Année = c(2026L, 2027L),
  Croissance = c(0.005, 0.010),
  Inflation = c(0.021, 0.018)
) |>
  gt::gt() |>
  gt::fmt_percent(columns = c(Croissance, Inflation), decimals = 1) |>
  gt::cols_label(Croissance = "Croissance du PIB", Inflation = "Inflation") |>
  gt::cols_align(align = "center", columns = everything()) |>
  #gt::data_color(columns = Croissance, palette = c("#f4a582", "#92c5de"), domain = c(0, 0.015)) |>
  #gt::data_color(columns = Inflation, palette = c("#92c5de", "#f4a582"), domain = c(0.015, 0.025)) |>
  gt::tab_header(title = "Prévisions macroéconomiques du Gouvernement") |>
  gt::tab_options(column_labels.font.weight = "bold",
                   heading.title.font.weight = "bold",
                   table.font.size = gt::px(14)) |>
  gt::opt_row_striping()
```


## Insee, note de conjoncture 10 septembre 2026

2026: croissance +0.4%

```{r}
ig_b("insee", "ndc-sept-2026", "annexe1-table1")
```


# Tableau de bord

## Insee

```{r echo = F}
"https://www.insee.fr/fr/statistiques/2107840" |>
  rvest::read_html() |>
  rvest::html_table(header = T, fill = T) |>
  pluck(1) |>
  gt::gt() |>
  gt::opt_interactive(use_search = F,
                      use_pagination = F,
                      use_pagination_info = F,
                      use_compact_mode = T,
                      page_size_default = 20,
                      page_size_values = c(5, 10, 15, 20)) |>
  gt::tab_footnote(
    footnote = gt::md(paste0("Date: ", format(Sys.time(), "%A %d %B %Y, %Hh%M"), ". Source: <https://www.insee.fr/fr/statistiques/2830613#tableau-figure1_radio1>"))
  ) |>
  gt::tab_options(table.width = "100%")
```



# Indicateurs macro

## Production industrielle

```{r}
ig_d("insee", "IPI-2021", "CZ-BE-mai-2017")
```




## Défaillances d'entreprises

```{r}
ig_d("bdf", "DIREN", "PE-IG-TP3")
```






# Indicateur du climat

## Emploi, Affaires

```{r}
ig_d("insee", "CLIMAT-AFFAIRES", "CLIMAT-EMPLOI")
```


## Indicateur de retournement

```{r}
ig_d("insee", "CLIMAT-AFFAIRES", "CLIMAT-RETOURNEMENT-2006")
```



# Info

- Les mots de la conjoncture. [pdf](https://www.insee.fr/fr/statistiques/fichier/1408431/Lexique_062013.pdf)


## Bases de données

```{r, echo = F}
theme_source_datasets("inflation-expectations") |>
  source_dataset_file_updates()
```




## Thèmes reliés

```{r, echo = F}
tribble(~ theme,
        "conjoncture",
        "macro-france") |>
  theme_file_updates()
```



```{r, echo = F}
#| output: asis
page_compile_line()
```
