---
title: Data on debt
subtitle: Data
lang: en
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: false
    toc: true
    theme: flatly
    embed-resources: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
editor: source
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))
debt <- tribble(
  ~source, ~dataset,
  "bis", "DSR",
  "bis", "CREDIT_GAP") %>%
  arrange(source, dataset)
```

# Debt Service Ratios

## By country

### United States

```{r}
ig_d("bis", "DSR", "USA")
```

### France

```{r}
ig_d("bis", "DSR", "FRA")
```

### Germany

```{r}
ig_d("bis", "DSR", "DEU")
```

## By sector

### Households

```{r}
ig_d("bis", "DSR", "FR-DE-US-H")
```



### Households

```{r}
ig_d("bis", "DSR", "FR-DE-US-N")
```


# Datasets

```{r, echo = F}
debt |>
  source_dataset_file_updates()
```

