---
title: Données sur les dépenses publiques
subtitle: Data
lang: fr
filters:
  - ../code/genderize-fr.lua
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: false
    toc: true
    theme: flatly
    embed-resources: false
editor: source
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "fr_FR.UTF-8"))
invisible(Sys.setenv(TZ = "Europe/Paris"))
`depenses-publiques` <- tribble(
  ~source, ~dataset,
  "insee", "T_3201",
  "insee", "T_7301") %>%
  arrange(source, dataset)
```



```{r, echo = F}
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("depenses-publiques.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("themes.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# sh ~/iCloud/website/website_short.sh
```




## Déficit primaire VS total

### Tous

```{r}
ig_d("insee", "t_compteapu_val", "PIB-D41-B9NF")
```



### 2005-

```{r}
ig_d("insee", "t_compteapu_val", "PIB-D41-B9NF-2005")
```



## Charge d'intérêt

```{r}
ig_d("insee", "t_compteapu_val", "PIB-D41")
```




## Détention par les non-résidents de la dette / CAC40

```{r}
ig_d("bdf", "DET", "detention-non-residents")
```



# Bibliographie

## En Français

{{< include ../public-debate/fr/Geerolf2025.qmd >}}

{{< include ../publications/fr/Geerolf2024b.qmd >}}

{{< include ../public-debate/fr/EcalleGeerolf2025.qmd >}}

{{< include ../publications/fr/Geerolf2021c.qmd >}}


## En Anglais

{{< include ../public-debate/en/Geerolf2025.qmd >}}

{{< include ../publications/en/Geerolf2024b.qmd >}}

{{< include ../working-papers/en/Geerolf2018a.qmd >}}

{{< include ../publications/en/Geerolf2013.qmd >}}


