---
title: Employment Data Analysis
subtitle: Data
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: false
    toc: true
    theme: flatly
    embed-resources: false
editor: source
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))
employment <- tribble(
  ~source, ~dataset,
  "bls", "jt",
  "bls", "la",
  "bls", "ln",
  "eurostat",  "namq_10_a10_e",
  "eurostat",  "nama_10_a10_e",
  "eurostat",  "nama_10_a64_e",
  "eurostat", "une_rt_m",
  "oecd", "STLABOUR",
  "oecd", "LFS_SEXAGE_I_R",
  "oecd", "ALFS_EMP",
  "oecd", "EPL_T") %>%
  arrange(source, dataset)
```

# Info

```{r, echo = F}
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("emploi.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("employment.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("industrie.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("industry.qmd")'
# sh ~/iCloud/website/website_short.sh
```

# Employment Rate

```{r, echo = F}
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -f STLABOUR_7.R
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -f STLABOUR_6.R
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -f STLABOUR_5.R
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -f STLABOUR_4.R
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -f STLABOUR_3.R
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -f STLABOUR_2.R
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -f STLABOUR_1.R
# cd ~/iCloud/website/data/oecd; /usr/local/bin/Rscript --vanilla _download_one_var2.R STLABOUR
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -f STLABOUR_7.R; /usr/local/bin/R -e 'quarto::quarto_render("STLABOUR.qmd")'
# sh ~/iCloud/website/website_short.sh
```

## France, Germany, Italy, US, Spain

### 15-74

```{r}
ig_d("oecd", "STLABOUR", "DEU-ESP-FRA-ITA-USA-LREM74TT")
```


### 25-54

```{r}
ig_d("oecd", "STLABOUR", "DEU-ESP-FRA-ITA-USA-LREM25TT")
```


## France, US

### 2000-

```{r}
ig_d("oecd", "STLABOUR", "FRA-USA-2000")
```

### 2019-

```{r}
ig_d("oecd", "STLABOUR", "FRA-USA-2019Q2-types")
```

# Unemployment

```{r, echo = F}
# cd ~/iCloud/website/data/eurostat; /usr/local/bin/Rscript --vanilla _download_one.R une_rt_m; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -f STLABOUR_7.R; /usr/local/bin/R -e 'quarto::quarto_render("STLABOUR.qmd")'
# sh ~/iCloud/website/website_short.sh
```

## France, Europe, US

```{r}
ig_d("oecd", "STLABOUR", "LRHUTTTT-A-USA-EA20-FRA")
```


```{r}
ig_d("oecd", "STLABOUR", "LRHUTTTT-M-USA-EA20-FRA-2005")
```





## France, US, Germany

```{r}
ig_d("oecd", "STLABOUR", "LRHUTTTT-Q-DEU-FRA-USA")
```

## France, Europe

```{r}
ig_d("eurostat", "une_rt_m", "EA-FR-1998")
```

## France, Germany, Italy, Spain, Netherlands

```{r}
ig_d("eurostat", "une_rt_m", "FR-DE-IT-ES-NL-PT")
```



## France, Germany, Italy, Spain, Europe


```{r}
ig_d("eurostat", "une_rt_m", "FR-DE-IT-ES-NL-EA20")
```


# Part-time employment

```{r}
ig_d("oecd", "FTPT_COMMON_INC", "FRA-NLD-DEU-EA20")
```

