---
title: Data on finance / stock market indices
metadata-files: 
  - _common.yml
---

```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))
finance <- tribble(
  ~source, ~dataset,
  "yahoo",  "CAC40",
  "yahoo",  "SP500",
  "yahoo", "indices") %>%
  arrange(source, dataset)
```

# Info

```{r, echo = F}
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("housing.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("immobilier.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("macro.qmd")'
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/housing.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/immobilier.html
# sh ~/iCloud/website/website_short.sh
```



# European finance

## Indices

```{r}
ig_d("yahoo", "indices", "GDAXI-IBEX-FCHI-1995-bind")
```

## Profits

```{r}
ig_d("eurostat", "nasq_10_nf_tr", "B2A3G-S11-BE-DE-FR-EA20-SCA-GVA")
```



# Datasets

```{r, echo = F}
`finance` |>
  source_dataset_file_updates()
```
