---
title: Données Clés de la Fonction Publique
subtitle: Data
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: false
    toc: true
    theme: flatly
    embed-resources: false
editor: source
---


```{r, echo = FALSE, message = FALSE}
source("../code/R-markdown/init_min.R")
knitr::opts_chunk$set(echo = T)
`fonction-publique` <- tribble(
  ~source, ~dataset,
  "dgafp", "FT12_FPE_FPH_FPT",
  "insee",  "EMPLOI-SALARIE-TRIM-NATIONAL",
  "insee",  "EMPLOI-BIT-TRIM") %>%
  arrange(source, dataset)

do.call(save, list("fonction-publique", file = "fonction-publique.RData"))
```


# Info

```{r, echo = F}
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("fonction-publique.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("emploi.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("finances-publiques.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("fonction-publique.qmd")'
# sh ~/iCloud/website/website_short.sh

tribble(~ theme,
        "fonction-publique",
        "finances-publiques",
        "dette-publique",
        "emploi") %>%
  theme_file_updates()
```

## Données sur les [fonction publique](https://fgeerolf.com/data/fonction-publique.html)

```{r, echo = F}
load_data("fonction-publique.RData")
`fonction-publique` %>%
  source_dataset_title_file_updates()
```

# Part dans la fonction publique

```{r, echo = F}
# cd ~/iCloud/website/data/insee; /usr/local/bin/Rscript --vanilla _download_one.R EMPLOI-SALARIE-TRIM-NATIONAL; /usr/local/bin/R -e 'quarto::quarto_render("EMPLOI-SALARIE-TRIM-NATIONAL.qmd")'
# sh ~/iCloud/website/website_short.sh

tribble(~source, ~ dataset,
        "insee", "EMPLOI-SALARIE-TRIM-NATIONAL") %>% 
  source_dataset_file_updates()
```





## Part dans l’emploi salarié

### DGAFP

```{r}
ig_d("dgafp", "FT12_FPE_FPH_FPT", "part-public")
```

### DGAFP

```{r}
ig_d("dgafp", "FT12_FPE_FPH_FPT", "secteurs")
```



## Part dans l’emploi salarié

```{r}
ig_d("insee", "EMPLOI-SALARIE-TRIM-NATIONAL", "part-emploi-public")
```

## Evolution du nombre de salariés

```{r}
ig_d("insee", "EMPLOI-SALARIE-TRIM-NATIONAL", "TOTENS-TOTPRIV-TOTPUB-2010Q4")
```



# Pyramide des âges

## Par versant au 31 décembre 2021

```{r}
ig_b("dgafp", "RA_2023", "figure3")
```

## Public vs Privé

```{r}
ig_b("dgafp", "RA_2022", "figure13-pyramide-ages-secteur-public")
```

## FPE - Fonctionnaires

```{r}
ig_b("dgafp", "RA_2022", "figure10-FPE-fonctionnaires")
```


## FPE - Contractuels

```{r}
ig_b("dgafp", "RA_2022", "figure10-FPE-contractuels")
```




