---
title: Données sur la macroéconomie de la Grèce
subtitle: Data
lang: fr
filters:
  - ../code/genderize-fr.lua
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: false
    toc: true
    theme: flatly
    embed-resources: false
editor: source
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "fr_FR.UTF-8"))
invisible(Sys.setenv(TZ = "Europe/Paris"))
`grece` <-tribble(
  ~source, ~dataset,
  "oecd", "QNA",
  "wdi", "NY.GDP.PCAP.PP.CD") %>%
  arrange(source, dataset)
```

# Comparaisons


## Europe

### Comparaison

```{r}
ig_d("eurostat", "nama_10_pc", "FR-EU-PL-HU-PL-EL-IT-using-groups-linear")
```



### Grèce, Pologne, Hongrie

```{r}
ig_d("eurostat", "tec00114", "EL-PL-HU")
```



### Grèce, Pologne, Hongrie, France, Italie

```{r}
ig_d("eurostat", "tec00114", "FR-DE-IT-ES-EL-PL-HU")
```

# Données

## Crise Dette

<https://youtu.be/9whoYlM0qkU?t=2617>

## Historique

Eurostat, Grèce: Swaps de taux...

Giórgos Papakonstantíno Eurogroup

Le chiffre qui vous a été envoyé il y a 2 semaines./ Défifcit officiel de 6% s'élevait en réalité en 13% du PIB...


Ceci arrive avant la crise en réalité.


