---
title: Data on Greece's macroeconomy
metadata-files: 
  - _common.yml
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))
`greece` <-tribble(
  ~source, ~dataset,
  "oecd", "QNA",
  "wdi", "NY.GDP.PCAP.PP.CD") %>%
  arrange(source, dataset)
```

```{r, echo = F}
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("greece.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("macro-france.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("macro.qmd")'
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/macro-france.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/inflation-france.html
# sh ~/iCloud/website/website_short.sh
```



# GDP Horse Races

```{r, echo = F}
# cd ~/iCloud/website/data/wdi; /usr/local/bin/Rscript --vanilla _dl_one_value.R NY.GDP.PCAP.PP.CD
# cd ~/iCloud/website/data/wdi; /usr/local/bin/Rscript --vanilla _dl_one_value.R NY.GDP.PCAP.CD
# cd ~/iCloud/website/data/wdi; /usr/local/bin/R -e 'quarto::quarto_render("NY.GDP.PCAP.PP.CD.qmd")'
# cd ~/iCloud/website/data/wdi; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -f QNA_9.R
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -e 'quarto::quarto_render("QNA_live.qmd")'
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -e 'quarto::quarto_render("QNA.qmd")'
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -f QNA_9.R
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -e 'quarto::quarto_render("QNA_live.qmd")'
# sh ~/iCloud/website/website_short.sh
```


## Europe

### Compare

```{r}
ig_d("eurostat", "nama_10_pc", "FR-EU-PL-HU-PL-EL-IT-using-groups-linear")
```



### Greece, Poland, Hungary

```{r}
ig_d("eurostat", "tec00114", "EL-PL-HU")
```



### Poland, Hungary, Greece, Germany, France, Italy, Spain, Netherlands

```{r}
ig_d("eurostat", "tec00114", "FR-DE-IT-ES-EL-PL-HU")
```





## World

### France, Germany, Greece, United States

```{r}
ig_d("oecd", "QNA_EXPENDITURE_CAPITA", "USA-EA20-GRC-2000-new-english")
```

### Greece

```{r}
ig_d("oecd", "QNA_EXPENDITURE_CAPITA", "FRA-PRT-ESP-GRC-ITA-1999")
```


# Balance of payments

## France vs. Greece

```{r}
ig_d("oecd", "BOP", "GRC-FRA-USA-1999-smoothed")
```


