---
title: Inflation in Europe since 2017
metadata-files: 
  - _common.yml
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))
`inflation-europe-2017` <- tribble(
  ~source, ~dataset,
  "ecb", "CES",
  "eurostat",  "prc_hicp_manr",
  "eurostat",  "prc_hicp_midx",
  "eurostat",  "prc_hicp_mmor",
  "eurostat",  "prc_hicp_inw",
  "eurostat",  "prc_hicp_cow",
  "eurostat",  "prc_ppp_ind",
  "eurostat",  "prc_hicp_ctrb",
  "eurostat", "nama_10_co3_p3") %>%
  arrange(source, dataset)
```

# All

```{r}
ig_d("eurostat", "prc_hicp_midx_Q", "CP00-DE-FR-IT-EA20-ES-2017T1-Q")
```



# Food

```{r}
ig_d("eurostat", "prc_hicp_midx", "DE-FR-IT-CP01-2017")
```

# Cars

## All Cars (CP071)

```{r}
ig_d("eurostat", "prc_hicp_midx", "DE-FR-IT-CP0711-2017")
```

## New Cars

```{r}
ig_d("eurostat", "prc_hicp_midx", "DE-FR-IT-EA20-ES-CP07111-2017")
```

## Old cars

```{r}
ig_d("eurostat", "prc_hicp_midx", "DE-FR-IT-EA20-ES-CP07112-2017")
```



# Rents

```{r}
ig_d("eurostat", "prc_hicp_midx", "DE-FR-IT-EA20-CP041-2017")
```

# Communications (CP08)

## Services (CP083)

```{r}
ig_d("eurostat", "prc_hicp_midx", "DE-FR-IT-NL-ES-CP0830-2017")
```

## Equipment (CP082)

```{r}
ig_d("eurostat", "prc_hicp_midx", "DE-FR-IT-EA20-ES-CP0820-2017")
```

## All

```{r}
ig_d("eurostat", "prc_hicp_midx", "DE-FR-IT-CP08-2017")
```


# Clothing (CP03)

Bridged overlap shouldn't be used except in exceptional circumstances according to Eurostat.

```{r}
ig_d("eurostat", "prc_hicp_aind", "DE-FR-IT-EA20-ES-CP03-2017")
```



