---
title: Data on investment 
subtitle: Data
lang: en
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: false
    toc: true
    theme: flatly
    embed-resources: false
editor: source
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))

investment <- tribble(
  ~source, ~dataset,
  "bea",  "FAAt207") %>%
  arrange(source, dataset)
```

# Info

```{r, echo = F}
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("investment.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("saving.qmd")'
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/investment.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/saving.html
# sh ~/iCloud/website/website_short.sh
```







