---
title: Why Economists Should Use Log Scales More Often
subtitle: Data
lang: en
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: false
    toc: true
    theme: flatly
    embed-resources: false
editor: source
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))
knitr::opts_chunk$set(echo = T)
`log-scales` <- tribble(
  ~source, ~dataset,
  "log", "microprocessor-trend-data",
   "ecb", "EXR") %>%
  arrange(source, dataset)
```

# Info

```{r, echo = F}
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("log.qmd")'
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/log.html
# sh ~/iCloud/website/website_short.sh
```


# Macro aggregates

## Real GDP

```{r}
ig_d("fred", "gdp", "GDPC1-both")
```

## Showing ratios

```{r}
ig_d("bea", "T10105", "gdp-conso-both")
```



# Microprocessor

```{r, echo = F}
# cd ~/iCloud/website/data/eurostat; /usr/local/bin/Rscript --vanilla _download_one.R nama_10_a64_e
# sh ~/iCloud/website/website_short.sh
```



## Transistors

```{r}
ig_d("log", "microprocessor-trend-data", "transistors-linear-log")
```

## Watts

```{r}
ig_d("log", "microprocessor-trend-data", "watts-linear-log")
```

## Cores

```{r}
ig_d("log", "microprocessor-trend-data", "cores-linear-log")
```

# Stocks

## Crédits aux particuliers

```{r}
ig_d("bdf", "immobilier", "encours-habitat-both")
```



# Pouvoir d'achat

```{r, echo = F}
# cd ~/iCloud/website/data/eurostat; /usr/local/bin/Rscript --vanilla _download_one.R nama_10_a64_e
# sh ~/iCloud/website/website_short.sh
```



## RDB

```{r}
ig_d("insee", "reve-niv-vie-pouv-achat-trim", "pouvoir-achat-both")
```

## RDB par UC

```{r}
ig_d("insee", "reve-niv-vie-pouv-achat-trim", "pouvoir-achat-UC-both")
```

## Salaire net à temps complet dans le privé

```{r}
ig_d("insee", "marc-salair-net-moy-sexe", "plot-bind")
```



# Other examples

```{r, echo = F}
# cd ~/iCloud/website/data/ecb; /usr/local/bin/Rscript --vanilla _download_one_csv.R EXR; /usr/local/bin/R -e 'quarto::quarto_render("EXR.qmd")'
# cd ~/iCloud/website/data/ecb; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data/ecb; /usr/local/bin/R -e 'quarto::quarto_render("EXR.qmd")'
# sh ~/iCloud/website/website_short.sh
```

## Exchange Rate, Argentine Peso

```{r}
ig_d("ecb", "EXR", "ARS-bind")
```


## Manufacturing investment

```{r}
ig_d("fred", "industry", "TLMFGCONS-both")
```



