---
title: Data on US Macro
metadata-files: 
  - _common.yml
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))
`macro-us` <- tribble(
  ~source, ~dataset,
  "fred",  "gdp",
  "fred",  "unr",
  "oecd",  "QNA",
  "oecd",  "SNA_TABLE1") %>%
  arrange(source, dataset)
```


# Info

```{r, echo = F}
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("macro-us.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("macro-france.qmd")'; 
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/macro-france.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/inflation-france.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/macro-us.html
# sh ~/iCloud/website/website_short.sh
```


# GDP, Consumption

```{r, echo = F}
# cd ~/iCloud/website/data/bea; /usr/local/bin/Rscript --vanilla _download_one_NIPA.R 10105 A; /usr/local/bin/Rscript --vanilla _download_one_NIPA.R 10105 Q; /usr/local/bin/R -e 'quarto::quarto_render("T10105.qmd")'
# sh ~/iCloud/website/website_short.sh
```

## Linear

```{r}
ig_d("bea", "T10105", "gdp-conso")
```

## Log

```{r}
ig_d("bea", "T10105", "gdp-conso-log")
```


# GDP

```{r, echo = F}
# cd ~/iCloud/website/data/bea; /usr/local/bin/Rscript --vanilla _download_one_NIPA.R 10106 A; /usr/local/bin/Rscript --vanilla _download_one_NIPA.R 10106 Q; /usr/local/bin/R -e 'quarto::quarto_render("T10106.qmd")'
# sh ~/iCloud/website/website_short.sh
```

## Real GDP

### Annual

```{r}
ig_d("bea", "T10106", "us-log-real-gdp-nipa-trend")
```

### Quarterly

```{r}
ig_d("bea", "T10106", "us-log-real-gdp-nipa-Q-2005")
```



## Output gap (% of potential output)

```{r}
ig_d("fred", "gdp", "output-gap-1965")
```

# Fiscal

```{r, echo = F}
# sh ~/iCloud/website/website_short.sh
```

## Budget surplus (% of GDP)

```{r}
ig_d("fred", "gdp", "surplus-gdp-1929-2019")
```


# Unemployment rate

```{r, echo = F}
# sh ~/iCloud/website/website_short.sh
```

## All

```{r}
ig_d("fred", "unr", "UNRATE")
```

## 1990-

```{r}
ig_d("fred", "unr", "UNRATE-1990")
```


## 2017-

```{r}
ig_d("fred", "unr", "UNRATE-17")
```

# Manufacturing Employment

```{r, echo = F}
# sh ~/iCloud/website/website_short.sh
```

## All

```{r}
ig_d("fred", "industry", "MANEMP-presidents")
```

## 1993-

```{r}
ig_d("fred", "industry", "MANEMP-presidents-1993")
```



# Net Exports

```{r, echo = F}
# cd ~/iCloud/website/data/bea; /usr/local/bin/Rscript --vanilla _download_one_NIPA.R 10105 A; /usr/local/bin/Rscript --vanilla _download_one_NIPA.R 10105 Q; /usr/local/bin/R -e 'quarto::quarto_render("T10105.qmd")'
# sh ~/iCloud/website/website_short.sh
```

## % of GDP

```{r}
ig_d("bea", "T10105", "net-exports-plain")
```



# Datasets

```{r, echo = F}
`macro-us` |>
  source_dataset_file_updates()
```