---
title: Données sur les matières premières
subtitle: Data
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: false
    toc: true
    theme: flatly
    embed-resources: false
editor: source
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "fr_FR.UTF-8"))
invisible(Sys.setenv(TZ = "Europe/Paris"))
knitr::opts_chunk$set(echo = T)
```


# Info

```{r, echo = F}
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("taux-dinteret.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("commodities.qmd")'
# sh ~/iCloud/website/website_short.sh
```

# Dernières données

## Sélection

```{r, echo = F}
temp <- "https://fr.investing.com/commodities/real-time-futures" |>
  rvest::read_html() |>
  rvest::html_table(header = T, fill = T) |>
  pluck(1) %>%
  select(-1)

temp |>
  filter(Nom %in% c("Pétrole brut WTI derived", "Pétrole Brent derived",
                    "XAU/USD", "Or derived")) |>
  gt()|>
    tab_options(
      quarto.disable_processing = TRUE
    ) |> 
  cols_align(
    align = "center") |>
  fmt_number(
    dec_mark = ",",
    sep_mark = ".",
    decimals = 2
  ) |>
  opt_interactive(
    use_search = F,
    use_pagination = F,
    use_pagination_info = F,
    use_compact_mode = T,
    page_size_default = 20,
    page_size_values = c(5, 10, 15, 20),
    use_resizers = T,
    use_highlight = T
  # ) |>
  # cols_width(
  #   c("country_code_2") ~ px(40),
  #   c("Current Rate") ~ px(120),
  #   c("Next Meeting") ~ px(140),
  #   c("Central Bank") ~ px(280),
  #   everything() ~ px(200)
  ) |>
  gt::tab_source_note(
    source_note = gt::md(paste0("Date: ", format(Sys.time(), "%A %d %B %Y, %Hh%M"), ". Source: <https://fr.investing.com/commodities/real-time-futures>"))
  ) |>
  gt::tab_options(table.width = "100%")
```

## Toutes les matières premières

```{r, echo = F}
temp |>
  gt()|>
    tab_options(
      quarto.disable_processing = TRUE
    ) |> 
  cols_align(
    align = "center") |>
  fmt_number(
    dec_mark = ",",
    sep_mark = ".",
    decimals = 2
  ) |>
  opt_interactive(
    use_search = F,
    use_pagination = F,
    use_pagination_info = F,
    use_compact_mode = T,
    page_size_default = 20,
    page_size_values = c(5, 10, 15, 20),
    use_resizers = T,
    use_highlight = T
  # ) |>
  # cols_width(
  #   c("country_code_2") ~ px(40),
  #   c("Current Rate") ~ px(120),
  #   c("Next Meeting") ~ px(140),
  #   c("Central Bank") ~ px(280),
  #   everything() ~ px(200)
  ) |>
  gt::tab_source_note(
    source_note = gt::md(paste0("Date: ", format(Sys.time(), "%A %d %B %Y, %Hh%M"), ". Source: <https://fr.investing.com/commodities/real-time-futures>"))
  ) |>
  gt::tab_options(table.width = "100%")
```


