---
title: Données météorologiques
subtitle: Données
lang: fr
filters:
  - ../code/genderize-fr.lua
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: false
    toc: true
    theme: flatly
    embed-resources: false
    include-in-header:
      - text: |
          <meta name="twitter:card" content="summary">
          <meta name="twitter:title" content="Données sur la météo">
          <meta name="twitter:description" content="Données sur la météo">
          <meta name="twitter:image" content="https://fgeerolf.com/files/meteo.jpg">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    include-after-body: ../statcounter.html
editor: source
---



```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "fr_FR.UTF-8"))
invisible(Sys.setenv(TZ = "Europe/Paris"))

meteo_station_heure_par_heure <- function(station_id = "07156",
                          from = Sys.Date() - lubridate::days(1),
                          to   = Sys.Date(),
                          interactive_limit = 12,
                          output = c("table", "data")) {

  output <- match.arg(output)

  data <- tibble(date = seq.Date(from = from, to = to, by = "day")) %>%
    
    mutate(
      url = paste0(
        "https://www.meteo60.fr/stations-releves/station-jour-csv?station_id=-",
        station_id,
        "&date=",
        format(date, "%d/%m/%Y")
      )
    ) %>%
    
    mutate(data = purrr::map(url, readr::read_delim, show_col_types = FALSE)) %>%
    
    mutate(data = purrr::map(data, \(df) {
      df$Vent_moyen <- as.character(df$Vent_moyen)
      df$Nebulosite <- as.character(df$Nebulosite)
      df
    })) %>%
    
    tidyr::unnest(data) %>%
    select(-url, -...15) %>%
    arrange(desc(date), desc(Heure_UTC)) %>%
    
    rename(
      heure = Heure_legale,
      T = Temperature,
      Vent = Vent_moyen,
      Humidité = Humidite_relative
    ) %>%
    
    mutate(
      heure = stringr::str_replace(heure, "^([0-9]{1,2}).*$", "\\1h"),
      
      Temps = tidyr::replace_na(Temps, ""),

      icon = dplyr::case_when(
        stringr::str_detect(Temps, regex("soleil|clair", TRUE)) ~ "☀️",
        stringr::str_detect(Temps, regex("nuage", TRUE)) ~ "⛅",
        stringr::str_detect(Temps, regex("pluie|averse", TRUE)) ~ "🌧️",
        stringr::str_detect(Temps, regex("orage", TRUE)) ~ "⛈️",
        stringr::str_detect(Temps, regex("brouillard|brume", TRUE)) ~ "🌫️",
        stringr::str_detect(Temps, regex("neige", TRUE)) ~ "❄️",
        TRUE ~ ""
      ),
      Temps = paste(icon, Temps)
    ) %>%
    
    select(
      date,
      heure,
      T,
      Temps,
      Vent,
      Vent_rafales,
      Direction,
      Humidité,
      everything()
    ) %>%
    select(
      -icon, -Heure_UTC
    ) %>%
    mutate(date = format(date, "%a %d"))

  # 👉 si l'utilisateur veut les données brutes
  if (output == "data") {
    return(data)
  }

  interactive_mode <- nrow(data) > interactive_limit

  gt_tbl <- data %>%
    gt::gt() %>%
    
    gt::fmt(
      columns = T,
      fns = function(x) sprintf("%.1f°", x)
    ) %>%
    
    gt::data_color(
      columns = T,
      colors = scales::col_numeric(
        palette = c("#2c7bb6", "#abd9e9", "#66bd63", "#fdae61", "#d7191c"),
        domain = NULL
      )
    ) %>%
    
    gt::cols_label(T = "T°",
                   heure = "h",
                   Vent_rafales = "Rafales") %>%
    
    gt::cols_align(
      "center",
      c(T, Vent, Humidité)
    ) %>%
    
    gt::cols_width(
      -c(Temps, Precipitations, Variation_pression,Pression_mer, date) ~ gt::px(60),
      c(Pression_mer) ~ gt::px(80),
      c(Variation_pression) ~ gt::px(90),
      c(date) ~ gt::px(70),
      c(Temps, Precipitations) ~ gt::px(225)
    ) %>%
    
    gt::tab_options(
      table.width = gt::pct(100),
      data_row.padding = gt::px(4)
    ) %>%
    
    gt::tab_footnote(
      footnote = gt::md(
        paste0(
          "Généré le ",
          format(Sys.time(), "%A %d %B %Y, %Hh%M"),
          " • Source : https://www.infoclimat.fr"
        )
      )
    )

  if (interactive_mode) {
    gt_tbl <- gt_tbl |>
      gt::opt_interactive(
        use_search = FALSE,
        use_pagination = TRUE,
        use_compact_mode = TRUE,
        page_size_default = interactive_limit
      )
  }

  gt_tbl
}
meteo_station_last_days <- function(station_id = "07156",
                                    n_days = 30,
                                    sun_threshold = 6,
                                    interactive_limit = 15,
                                    output = c("table", "data")) {

  output <- match.arg(output)

  stopifnot(n_days > 0)

  today <- Sys.Date()
  start_date <- today - n_days + 1

  months_needed <- seq(lubridate::floor_date(start_date, "month"),
                       lubridate::floor_date(today, "month"),
                       by = "1 month")

  data <- purrr::map_dfr(months_needed, \(d) {

    url <- paste0(
      "https://www.meteo60.fr/stations-releves/station-mois-csv?station_id=",
      station_id,
      "&mois=", lubridate::month(d),
      "&annee=", lubridate::year(d) - 2000
    )

    readr::read_delim(url, show_col_types = FALSE) %>%
      tibble::as_tibble() %>%
      dplyr::select(-7) %>%
      dplyr::mutate(
        jour = readr::parse_number(Jour),
        date = as.Date(ISOdate(lubridate::year(d),
                               lubridate::month(d),
                               jour))
      )
  }) %>%
    dplyr::filter(date >= start_date & date <= today) %>%
    dplyr::arrange(desc(date)) %>%

    dplyr::mutate(
      # 📅 Jour compact
      date = format(date, "%a %d", locale = "fr_FR.UTF-8"),

      # 🌡️ noms courts
      `T° min` = Temperature_mini,
      `T° moy` = Temperature_moy,
      `T° max` = Temperature_maxi,

      # ☔ pluie
      pluie_icon = ifelse(!(Precipitations %in% c("0.0", "0.0*")), "☔", ""),

      # ☀️ ensoleillement élevé
      sun_minutes = lubridate::period_to_seconds(lubridate::hm(gsub("h", ":", Ensoleillement))) / 60,
      soleil_icon = dplyr::if_else(sun_minutes >= sun_threshold * 60, "☀️", "", missing = ""),

      Meteo = stringr::str_trim(paste(pluie_icon, soleil_icon))
    ) %>%
    
    dplyr::select(
      date,
      `T° min`,
      `T° moy`,
      `T° max`,
      Meteo,
      Precipitations,
      Ensoleillement
    )

  # 👉 sortie données
  if (output == "data") {
    return(data)
  }

  interactive_mode <- nrow(data) > interactive_limit

  gt_tbl <- data %>%
    gt::gt() %>%

    gt::cols_align(
      "center",
      c(`T° min`, `T° moy`, `T° max`, Precipitations)
    ) %>%

    gt::data_color(
      columns = `T° moy`,
      colors = scales::col_numeric(
        palette = c("#2c7bb6", "#abd9e9", "#66bd63", "#fdae61", "#d7191c"),
        domain = NULL
      )
    ) %>%

    gt::cols_label(
      Meteo = "",
      Precipitations = "Pluie (mm)",
      Ensoleillement = "Soleil"
    ) %>%

    gt::tab_options(
      table.width = gt::pct(100),
      data_row.padding = gt::px(4)
    ) %>%
    
    gt::cols_width(
      -c(Precipitations, Ensoleillement, date) ~ gt::px(55),
      c(date) ~ gt::px(70),
      c(Precipitations, Ensoleillement) ~ gt::px(80)
    ) %>%

    gt::tab_footnote(
      footnote = gt::md(
        paste0(
          n_days, " derniers jours • Généré le ",
          format(Sys.time(), "%d %B %Y"),
          " • Source : https://www.infoclimat.fr"
        )
      )
    )

  if (interactive_mode) {
    gt_tbl <- gt_tbl |>
      gt::opt_interactive(
        use_search = FALSE,
        use_pagination = TRUE,
        use_compact_mode = TRUE,
        page_size_default = interactive_limit
      )
  }

  gt_tbl
}


## cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
## cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("pouvoir-achat.qmd")'
## sh ~/iCloud/website/website_short.sh
```


# Paris-Montsouris (07156)

## Par heure, 2 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_heure_par_heure("07156", from = Sys.Date() - 2)
```



## 30 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_last_days("07156", 30)
```



# Lille (07015)

## Par heure, 2 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_heure_par_heure("07015", from = Sys.Date() - 2)
```



## 30 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_last_days("07015", 30)
```

# Montagne

## Chamonix (07490)

### Par heure, 2 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_heure_par_heure("07490", from = Sys.Date() - 2)
```



### 30 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_last_days("07490", 30)
```


# Région Parisienne

## Roissy CDG (07157)

### Par heure, 2 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_heure_par_heure("07157", from = Sys.Date() - 2)
```



### 30 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_last_days("07157", 30)
```

# Marseille Marignane (07650)

## Par heure, 2 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_heure_par_heure("07650", from = Sys.Date() - 2)
```

## 30 derniers jours

```{r echo = F, message = F, warning = F}
meteo_station_last_days("07650", 30)
```
