---
title: Data on money
subtitle: Data
lang: en
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: false
    toc: true
    theme: flatly
    embed-resources: false
editor: source
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))
money <- tribble(
  ~source, ~dataset,
  "bdf",  "FM",
  "bdf",  "MIR",
  "bdf",  "MIR1",
  "bis",  "CBPOL",
  "ecb", "BSI",
  "ecb", "BSI_PUB",
  "ecb",  "FM",
  "ecb", "ILM",
  "ecb", "ILM_PUB",
  "ecb", "liq_daily",
  "ecb",  "MIR",
  "ecb", "RAI",
  "ecb",  "SUP",
  "ecb",  "YC",
  "ecb",  "YC_PUB",
  "eurostat", "ei_mfir_m",
  "eurostat", "irt_st_m",
  "fred",  "r",
  "oecd",  "MEI",
  "oecd",  "MEI_FIN") %>%
  arrange(source, dataset)
```


# ECB

## M1

```{r}
ig_d("ecb", "BSI", "M1-E")
```


## M2-M1

```{r}
ig_d("ecb", "BSI", "M2-M1-E")
```

## M3-M2

```{r}
ig_d("ecb", "BSI", "M3-M2-E")
```





# Related papers

{{< include ../publications/monetary-policy.qmd >}}






