---
title: Données sur le niveau de vie
metadata-files: 
  - _common_fr.yml
---



```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "fr_FR.UTF-8"))
invisible(Sys.setenv(TZ = "Europe/Paris"))
## cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
## cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("pouvoir-achat.qmd")'
## sh ~/iCloud/website/website_short.sh
`niveau-de-vie` <- tribble(
  ~source, ~dataset,
  "insee", "reve-niv-vie-individu-activite",
  "insee", "reve-niv-vie-pouv-achat-trim",
  "insee", "reve-conso-evo-dep-pa",
  "insee", "t_men_val",
  "insee", "econ-gen-revenu-dispo-pouv-achat-2") %>%
  arrange(source, dataset)
```


# Thèmes reliés

```{r, echo = F}
tribble(~ theme,
        "pouvoir-achat", 
        "pouvoir-achat-2017",
        "inflation-france",
        "inflation-france-2017") |>
  theme_file_updates()
```




# Chiffres officiels de l'Insee

## Niveau de vie médian selon le statut d’activité

```{r echo = F}
"https://www.insee.fr/fr/statistiques/2415628" |>
  rvest::read_html() |>
  rvest::html_table(header = T, fill = T) |>
  pluck(1) |>
  gt::gt() |>
  gt::cols_width(1 ~ gt::px(300), everything() ~ gt::px(90)) |>
  gt::opt_interactive(use_search = F,
                      use_pagination = F,
                      use_pagination_info = F,
                      use_compact_mode = T,
                      page_size_default = 20,
                      page_size_values = c(5, 10, 15, 20)) |>
  gt::tab_footnote(
    footnote = gt::md(paste0("Date: ", format(Sys.time(), "%A %d %B %Y, %Hh%M"), ". Source: <https://www.insee.fr/fr/statistiques/2415628#figure1_radio1>"))
  ) |>
  gt::tab_options(table.width = "100%")
```



## Niveau de vie moyen selon le statut d’activité

```{r echo = F}
"https://www.insee.fr/fr/statistiques/2415628" |>
  rvest::read_html() |>
  rvest::html_table(header = T, fill = T) |>
  pluck(2) |>
  gt::gt() |>
  gt::cols_width(1 ~ gt::px(300), everything() ~ gt::px(90)) |>
  gt::opt_interactive(use_search = F,
                      use_pagination = F,
                      use_pagination_info = F,
                      use_compact_mode = T,
                      page_size_default = 20,
                      page_size_values = c(5, 10, 15, 20)) |>
  gt::tab_footnote(
    footnote = gt::md(paste0("Date: ", format(Sys.time(), "%A %d %B %Y, %Hh%M"), ". Source: <https://www.insee.fr/fr/statistiques/2415628#figure1_radio2>"))
  ) |>
  gt::tab_options(table.width = "100%")
```


# Bases de données

```{r, echo = F}
`niveau-de-vie` |>
  source_dataset_file_updates()
```

