---
title: Data on Phillips curves
metadata-files: 
  - _common.yml
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("phillips.qmd")'
# cd ~/iCloud/website/data/eurostat; /usr/local/bin/R -e 'quarto::quarto_render("phillips.qmd")'
# sh ~/iCloud/website/website_short.sh
phillips <- tribble(
  ~source, ~dataset,
  "eurostat",  "tipsna62",
  "eurostat",  "phillips",
  "fred",  "phillips",
  "wdi",  "phillips",
  "ilo",  "phillips",
  "oecd",  "phillips",
  "gfd", "phillips") %>%
  arrange(source, dataset)
```


# Bibliography

```{r, echo = F}
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("phillips.qmd")';
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("macro.qmd")';
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/macro-france.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/inflation-france.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/macro-us.html
# sh ~/iCloud/website/website_short.sh
```

## English

{{< include ../publications/en/Geerolf2021b.qmd >}}

{{< include ../publications/en/Geerolf2021a.qmd >}}

{{< include ../working-papers/en/Geerolf2020.qmd >}}

## French

{{< include ../publications/fr/Geerolf2021b.qmd >}}

{{< include ../publications/fr/Geerolf2021a.qmd >}}

# Original Phillips curve, UK

## United Kingdom

### old

```{r}
ig_d("fred", "phillips", "uk-1860-1915-colors")
```

### New

```{r}
ig_d("fred", "phillips", "uk-1860-1915-colors-new2")
```

## With Prices

```{r}
ig_d("fred", "phillips", "uk-1860-1915-with-prices")
```

# Eurostat

## Greece

```{r}
ig_d("eurostat", "phillips", "nama-10-lp-ulc-EL")
```

## France

```{r}
ig_d("eurostat", "phillips", "nama-10-lp-ulc-FR")
```



# Datasets

```{r, echo = F}
`phillips` |>
  source_dataset_file_updates()
```
