---
title: Data on productivity
subtitle: Data
lang: en
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: false
    toc: true
    theme: flatly
    embed-resources: false
editor: source
---



```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))
`productivity` <- tribble(
  ~source, ~dataset,
  "oecd",  "PDBI_I4",
  "oecd",  "ULC_EEQ") %>%
  arrange(source, dataset)
```


# Info

```{r, echo = F}
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("productivite.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("productivity.qmd")'
# sh ~/iCloud/website/website_short.sh
```


# Hours worked

## Measurement problems

```{r}
ig_d("oecd", "ANHRS", "FRA-USA-DEU")
```

## Total & Dependent

```{r}
ig_d("oecd", "ANHRS", "FRA-USA-DEU")
```

## Productivity levels

```{r}
ig_d("oecd", "PDB_LV", "THRSPOP-EU-PEHRS")
```



## Total Employment

```{r}
ig_d("oecd", "ANHRS", "TE-DEU-FRA-ITA-USA-ESP")
```

## For fun: sunshine duration / year

Number of hours per year: `r 365*24` hours/year.

```{r}
ig_b("productivity", "sunshine-duration-per-year", ext = ".jpeg")
```

# Unit Labor Costs

```{r, echo = F}
# cd ~/iCloud/website/data/oecd; /usr/local/bin/Rscript --vanilla _download_data.R ULC_EEQ; /usr/local/bin/R -e 'quarto::quarto_render("ULC_EEQ.qmd")'
# sh ~/iCloud/website/website_short.sh
```



## ULC, wages, GDP per person

```{r}
ig_d("oecd", "ULC_EEQ", "EA-US-FRA-all-2019-Q4")
```






