---
title: Données sur la redistribution
metadata-files: 
  - _common_fr.yml
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "fr_FR.UTF-8"))
invisible(Sys.setenv(TZ = "Europe/Paris"))
redistribution <- tribble(
  ~source, ~dataset,
  "insee", "IA88",
  "insee", "RPM2021_D2") %>%
  arrange(source, dataset)
```

# Redistribution élargie

## Données Gini

```{r}
ig_b("insee", "RPM2021", "D2", "fig8")
```


## Décomposition Gini

```{r}
ig_b("insee", "IA88", "fig4")
```



## Comptes nationaux distribués

```{r}
ig_b("insee", "RPM2021", "D2", "table2")
```



## Ménages pauvres et aisés avant et après redistribution élargie

```{r}
ig_b("insee", "IA88", "fig2")
```

# Taux d'imposition

## Données

```{r}
ig_d("insee", "RPM2021_D2", "comparatif")
```

## Autre visualisation

```{r}
ig_b("redistribution", "redistribution-decile")
```



# Thèmes reliés

```{r, echo = F}
tribble(~ theme,
        "inegalites",
        "redistribution") |>
  theme_file_updates()
```


# Bases de données

```{r, echo = F}
`redistribution` |>
  source_dataset_file_updates()
```


# Bibliographie en lien

## Français

{{< include ../public-debate/fr/Geerolf2026.qmd >}}

{{< include ../public-debate/fr/Geerolf2025b.qmd >}}



