---
title: Statistiques sur les retraites
subtitle: Data
lang: fr
filters:
  - ../code/genderize-fr.lua
author:
  - name: François Geerolf
    url: https://fgeerolf.com
format:
  html:
    code-fold: false
    toc: true
    theme: flatly
    embed-resources: false
editor: source
---


```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "fr_FR.UTF-8"))
invisible(Sys.setenv(TZ = "Europe/Paris"))

retraites <- tribble(
  ~source, ~dataset,
  "insee",  "DECES-MORTALITE",
  "ipp",  "revalorisation_pension") %>%
  arrange(source, dataset)
```

# Info

```{r, echo = F}
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("retraites.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("retraites.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("wages.qmd")'
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/retraites.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/macro-france.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/inflation-france.html
# sh ~/iCloud/website/website_short.sh
```

# Espérance de vie

## Tous

```{r}
ig_d("insee", "DECES-MORTALITE", "esperance-vie")
```

## 1981-

```{r}
ig_d("insee", "DECES-MORTALITE", "esperance-vie-1981")
```

## Par CSP

```{r}
ig_b("insee", "ip2005", "fig3")
```

# Revalorisation des retraites

## Pensions vs. Indice FP

### 1999-

```{r}
ig_d("ipp", "revalorisation_pension", "merge-indicefp")
```

### 2012-

```{r}
ig_d("ipp", "revalorisation_pension", "merge-indicefp-2012")
```


### 2017-

```{r}
ig_d("ipp", "revalorisation_pension", "merge-indicefp-2017")
```




