---
title: Global Trade Data
metadata-files: 
  - _common.yml
---

```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))
`trade` <-tribble(
  ~source, ~dataset,
  "eurostat", "bop_gdp6_q",
  "eurostat",  "nama_10_a10_e",
  "eurostat",  "namq_10_a10_e",
  "eurostat",  "nama_10_a10",
  "eurostat",  "namq_10_a10",
  "eurostat",  "nama_10_gdp",
  "eurostat",  "namq_10_gdp",
  "eurostat",  "nama_10_lp_ulc",
  "eurostat",  "namq_10_lp_ulc",
  "eurostat",  "namq_10_pc",
  "eurostat", "nasa_10_nf_tr",
  "eurostat", "nasq_10_nf_tr",
  "eurostat", "tipsii40") %>%
  arrange(source, dataset)

# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("trade.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("macro-france.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("macro.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("interest-rates.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("monetary-policy.qmd")'
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/macro-france.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/trade.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/inflation-france.html
# sh ~/iCloud/website/website_short.sh
```



# Net Exports

## OECD

```{r}
ig_d("oecd", "QNA_EXPENDITURE_NATIO_CURR", "B11-B1GQ-EA20-USA-FRA-DEU-1990")
```
