---
title: Comparing the United States and Europe
metadata-files: 
  - _common.yml
---

```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))
knitr::opts_chunk$set(echo = T)
`us-eu` <- tribble(
  ~source, ~dataset,
  "bis", "CBPOL_D",
  "oecd", "BOP",
  "oecd",  "QNA_EXPENDITURE_CAPITA",
  "wdi", "NY.GDP.PCAP.CD",
  "wdi", "NY.GDP.PCAP.PP.CD",
  "wdi", "NY.GDP.MKTP.PP.CD") %>%
  arrange(source, dataset)
```

# Info

```{r, echo = F}
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("us-eu.qmd")'
# sh ~/iCloud/website/website_short.sh
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("salaires.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("wages.qmd")'
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/macro-france.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/us-eu.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/macro-us.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/inflation-france.html
# sh ~/iCloud/website/website_short.sh
```

# GDP Data

```{r, echo = F}
# cd ~/iCloud/website/data/oecd; /usr/local/bin/Rscript --vanilla _download_new.R OECD.SDD.NAD DSD_NAMAIN1 QNA_EXPENDITURE_CAPITA; /usr/local/bin/R -e 'quarto::quarto_render(input = "QNA_EXPENDITURE_CAPITA.qmd")'
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# sh ~/iCloud/website/website_short.sh
```

## In volume

```{r}
ig_d("oecd", "QNA_EXPENDITURE_CAPITA", "USA-EA20-1999")
```

## Current Dollars

```{r}
ig_d("wdi", "NY.GDP.PCAP.CD", "XC-US-PIB-dollars")
```

## With PPA

```{r}
ig_d("wdi", "NY.GDP.PCAP.PP.CD", "US-FR-XC-GDP-PPP-1990")
```

## Compare

### Eurozone

```{r}
ig_d("wdi", "NY.GDP.MKTP.PP.CD", "CN-US-XC-PPP-current")
```

### EU27

```{r}
ig_d("wdi", "NY.GDP.MKTP.PP.CD", "CN-US-EU-PPP-current")
```

# International: NX, CA, IIP

```{r, echo = F}
# cd ~/iCloud/website/data/oecd; /usr/local/bin/Rscript --vanilla _download_new.R OECD.SDD.TPS DSD_BOP BOP; /usr/local/bin/R -e 'quarto::quarto_render(input = "BOP.qmd")'
# cd ~/iCloud/website/data/oecd; /usr/local/bin/Rscript --vanilla _download_new.R OECD.SDD.NAD DSD_NAMAIN1 QNA_EXPENDITURE_NATIO_CURR; /usr/local/bin/R -e 'quarto::quarto_render(input = "QNA_EXPENDITURE_NATIO_CURR.qmd")'
# cd ~/iCloud/website/data/oecd; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# sh ~/iCloud/website/website_short.sh
```

## Current Account

### EA20 vs USA

```{r}
ig_d("oecd", "BOP", "CA-USA-EA20-2012")
```

### EU27 vs USA

```{r}
ig_d("oecd", "BOP", "CA-EU27-USA-1999")
```


## Net Exports

```{r}
ig_d("oecd", "QNA_EXPENDITURE_NATIO_CURR", "B11-B1GQ-EA20-USA-1970")
```

## International Investment Position

```{r}
ig_d("imf", "IFR_BP6_USD", "U2-US-1999")
```



# Public Debt, public deficit

```{r, echo = F}
# cd ~/iCloud/website/data/imf; /usr/local/bin/Rscript --vanilla _download_one.R FM GGXCNL_G01_GDP_PT; /usr/local/bin/R -e 'quarto::quarto_render("GGXCNL_G01_GDP_PT.qmd")'
# cd ~/iCloud/website/data/imf; /usr/local/bin/Rscript --vanilla _download_one.R FM GGXONLB_G01_GDP_PT; /usr/local/bin/R -e 'quarto::quarto_render("GGXONLB_G01_GDP_PT.qmd")'
# cd ~/iCloud/website/data/imf; /usr/local/bin/Rscript --vanilla _download_one.R FM GGCB_G01_PGDP_PT
# cd ~/iCloud/website/data/imf; /usr/local/bin/Rscript --vanilla _download_one.R FM GGCBP_G01_PGDP_PT
# cd ~/iCloud/website/data/imf; /usr/local/bin/Rscript --vanilla _download_one.R FM GGXCNL_G01_GDP_PT
# cd ~/iCloud/website/data/imf; /usr/local/bin/Rscript --vanilla _download_one.R FM GGXONLB_G01_GDP_PT
# cd ~/iCloud/website/data/imf/; /usr/local/bin/R -e 'quarto::quarto_render("GGCB_G01_PGDP_PT.qmd")'
# cd ~/iCloud/website/data/imf/; /usr/local/bin/R -e 'quarto::quarto_render("GGCBP_G01_PGDP_PT.qmd")'
# cd ~/iCloud/website/data/imf/; /usr/local/bin/R -e 'quarto::quarto_render("GGXCNL_G01_GDP_PT.qmd")'
# cd ~/iCloud/website/data/imf/; /usr/local/bin/R -e 'quarto::quarto_render("GGXONLB_G01_GDP_PT.qmd")'
# sh ~/iCloud/website/website_short.sh
# sh ~/iCloud/website/website_short.sh
```

## Deficit

```{r}
ig_d("imf", "GGXCNL_G01_GDP_PT", "U2-US-2010-french")
```



## New

```{r}
ig_d("imf", "G_XWDG_G01_GDP_PT", "US-U2-1999-2023")
```

# Monetary policy

## Policy rates

```{r}
ig_d("bis", "CBPOL_D", "US-XM-2022-dates2-deposit")
```



## Size of the balance sheet

```{r}
ig_d("fred", "money", "assets-ECB-FED")
```


# Datasets

```{r, echo = F}
`us-eu` |>
  source_dataset_file_updates()
```


