---
title: "Data on wealth"
metadata-files: 
  - _common.yml
---

```{r, echo = FALSE, message = FALSE}
source(here::here("_rinit.R"))
invisible(Sys.setlocale("LC_TIME", "en_US.UTF-8"))
invisible(Sys.setenv(TZ = "America/Los_Angeles"))

# (was: wealth <- tribble(~source, ~dataset, ...) -- now auto: theme_source_datasets("wealth"))
```


# Info

```{r, echo = F}
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("index.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("epargne.qmd")'
# cd ~/iCloud/website/data; /usr/local/bin/R -e 'quarto::quarto_render("saving.qmd")'
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/epargne.html
# sh ~/iCloud/website/website_short.sh; open https://fgeerolf.com/data/saving.html
# sh ~/iCloud/website/website_short.sh
```


# U.S.

```{r, echo = F}
# cd ~/iCloud/website/data/fred; /usr/local/bin/R -f "saving.R"
# cd ~/iCloud/website/data/fred; /usr/local/bin/R -f "saving.R"; /usr/local/bin/R -e 'quarto::quarto_render("saving.qmd")'
# sh ~/iCloud/website/website_short.sh
```

## Net worth

```{r}
ig_d("frb", "B1", "net-worth")
```


## Book value vs. market value

```{r}
ig_r("PikettyZucman2014", "PZ-A100-US")
```



# Nonfinancial Corporations

## Tobin's Q for Nonfinancial Corporations

```{r}
ig_d("frb", "B103", "tobin-q")
```



## Equipment, Real estate

```{r}
ig_d("frb", "B103", "corporate-bonds-equities")
```

# Households and non profits

## Current cost VS market value housing

```{r}
ig_d("frb", "B101", "structures-real-estate")
```


## Corporate Equities, Pensions, Real Estate

```{r}
ig_d("frb", "B101", "line-3-23-27")
```

# Datasets

```{r, echo = F}
theme_source_datasets("wealth") |>
  source_dataset_file_updates()
```


