

## English

{{< include ../publications/en/Blot2025.qmd >}}

{{< include ../publications/en/Geerolf2024c.qmd >}}

{{< include ../publications/en/Geerolf2024b.qmd >}}

{{< include ../publications/en/Geerolf2024a.qmd >}}

{{< include ../publications/en/Geerolf2023c.qmd >}}

{{< include ../publications/en/Blot2023d.qmd >}}

{{< include ../publications/en/Blot2023c.qmd >}}

{{< include ../publications/en/Blot2023b.qmd >}}

{{< include ../publications/en/Blot2023a.qmd >}}

{{< include ../publications/en/Blot2022.qmd >}}

{{< include ../publications/en/Geerolf2022b.qmd >}}

{{< include ../publications/en/Geerolf2022.qmd >}}

- "The Phillips Curve: a Relation between Real Exchange Rate Growth and Unemployment." F. Geerolf, January 2020. [[pdf](https://fgeerolf.com/phillips.pdf)]

## French

{{< include ../publications/fr/Geerolf2024c.qmd >}}

{{< include ../publications/fr/Geerolf2024b.qmd >}}

{{< include ../publications/fr/Geerolf2024a.qmd >}}

{{< include ../publications/fr/Geerolf2023c.qmd >}}

{{< include ../publications/fr/Geerolf2023b.qmd >}}

- "Une analyse macroéconomique de l'inflation.", C. Antonin & F. Geerolf, In la Jaune et la Rouge n°783, mars 2023. [[pdf](https://www.lajauneetlarouge.com/wp-content/uploads/2023/02/La_Jaune_et_la_Rouge_783_41-44.pdf)] [[html](https://www.lajauneetlarouge.com/analyse-macroeconomique-de-linflation-et-de-la-pertinence-de-nos-modeles/)]

{{< include ../publications/fr/Geerolf2023a.qmd >}}

- "Qui va payer cette facture énergétique ?" F. Geerolf, Interview a priori, décembre 2022. [[html](https://a-prioris.fr/hauteur-de-vue/francois-geerolf-qui-va-payer-cette-facture-energetique)]

- "Inflation en Europe : les conséquences sociales de la guerre en Ukraine." G. Allègre, F. Geerolf, X. Timbeau, Blog de l'OFCE, juillet 2022. [[html](https://www.ofce.sciences-po.fr/blog/inflation-en-europe-les-consequences-sociales-de-la-guerre-en-ukraine/)]

- Inflation et pouvoir d'achat : it's the politics, stupid! F. Geerolf & P. Jacquet, Relançons le débat économique, juin 2022. [[pdf](https://lecercledeseconomistes.fr/wp-content/uploads/2022/07/rlde-2022-25-geerolfjacquet.pdf)] [[html](https://lecercledeseconomistes.fr/inflation-et-pouvoir-dachat-its-the-politics-stupid/)]

{{< include ../publications/fr/Geerolf2022.qmd >}}

- "Le keynésianisme doit-il faire l'économie de la courbe de Phillips ?" F. Geerolf, In L'économie mondiale 2022, La Découverte, p.73-86, septembre 2021. [[pdf](http://www.cepii.fr/PDF_PUB/em/2022/em2022-05.pdf)] [[slides](http://www.cepii.fr/docs/files/reunions/communications/em2022/Economie%20Mondiale%202022_Geerolf.pdf)]

- "La courbe de Phillips n'est pas celle que vous croyez." F. Geerolf, La Lettre du CEPII, n°417, avril 2021. [[pdf](http://www.cepii.fr/PDF_PUB/lettre/2021/let417.pdf)] [[html](http://www.cepii.fr/CEPII/fr/publications/lettre/abstract.asp?NoDoc=12974)]